name: S3 upload
description: "Upload files to s3 bucket"

inputs:
  AWS_ROLE_TO_ASSUME:
    required: false
    description: "AWS role to be assumed during workflow execution"
  AWS_SESSION_NAME:
    required: false
    description: "Respective session name for the assumed role"
  region:
    required: false
    type: string
    default: "us-east-1"
  source-folders:
    description: "List of folders to add to the build artifact"
    required: false
    default: |
      build
  artifact-version:
    description: "Tag version , e.g. 'v1.2.3'"
    required: true
    type: string
  bucket-name:
    required: true
    type: string

runs:
  using: "composite"

  steps:
  - name: Zip Source Folders
    shell: bash
    run: |
      targets="${{ inputs.source-folders }}"
      for target in $targets
      do
        echo "Adding '$target' to archive..."
        zip -r -q ${{ inputs.artifact-version }}.zip $target
      done

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1-node16
    with:
      aws-region: ${{ inputs.region }}
      role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
      role-session-name: ${{ inputs.AWS_SESSION_NAME }}

  - name: Copying files to S3 Bucket
    shell: bash
    env:
      BUCKET_NAME: ${{ inputs.bucket-name }}
      REPO_NAME: ${{ github.event.repository.name }}
    run: |
      echo "Bucket Name == " ${BUCKET_NAME}
      echo "Archive Name == " ${{ inputs.artifact-version }}.zip
      aws s3 cp ${{ inputs.artifact-version }}.zip s3://${BUCKET_NAME}/gha-artifacts/${REPO_NAME}/${{ inputs.artifact-version }}.zip
